version: '3'

services:
  db:
    image: mysql/mysql-server:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  cpatracker:
    depends_on:
      - db
    build: ./fpm-alpine
    container_name: cpatracker
    restart: unless-stopped
    env_file: .env
    volumes:
      - cpatracker:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - cpatracker
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - cpatracker:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

volumes:
  cpatracker:
  dbdata:

networks:
  app-network:
    driver: bridge
